/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author allen
 */
import javax.swing.JOptionPane;
import javax.swing.*;

public class VendingMachineFrame extends javax.swing.JPanel {

    private Beverage coke = new Coke();
    private Beverage water = new Water();
    private Beverage coffee = new Coffee();
    private Snack cheetos = new Cheetos();
    private Snack doritos = new Doritos();
    private Snack burger = new Burger();
    private Product selectedProduct;

    private double totalMoney = 0.0;

    private int cokeAvailability = 10;
    private int waterAvailability = 10;
    private int coffeeAvailability = 10;
    private int cheetosAvailability = 10;
    private int doritosAvailability = 10;
    private int burgerAvailability = 10;

    /**
     * Creates new form VendingMachineFrame
     */
    public VendingMachineFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ButtonPanel = new javax.swing.JPanel();
        TwentyphpButton = new javax.swing.JButton();
        HundredphpButton = new javax.swing.JButton();
        TenphpButton = new javax.swing.JButton();
        ThirtyphpButton = new javax.swing.JButton();
        FiftyphpButton = new javax.swing.JButton();
        LazatinMachineLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        TotalBalance = new javax.swing.JLabel();
        CashOutButton = new javax.swing.JButton();
        BalanceLabel = new javax.swing.JLabel();
        ProductPanel = new javax.swing.JPanel();
        BeveragesLabel = new javax.swing.JLabel();
        SnacksMachineLabel = new javax.swing.JLabel();
        BuyCheetosButton = new javax.swing.JButton();
        BuyBurgerButton = new javax.swing.JButton();
        BuyDoritosButton = new javax.swing.JButton();
        CokeLabel = new javax.swing.JLabel();
        WaterLabel = new javax.swing.JLabel();
        CoffeeLabel = new javax.swing.JLabel();
        BurgerLabel = new javax.swing.JLabel();
        DoritosLabel = new javax.swing.JLabel();
        CheetosLabel = new javax.swing.JLabel();
        BuyCoffeeButton = new javax.swing.JButton();
        BuyWaterButton = new javax.swing.JButton();
        BuyCokeButton = new javax.swing.JButton();
        DragonFruitStocksLabel = new javax.swing.JLabel();
        WaterStocksLabel = new javax.swing.JLabel();
        CokeStocksLabel = new javax.swing.JLabel();
        CheetosStocksLabel = new javax.swing.JLabel();
        DoritosStocksLabel = new javax.swing.JLabel();
        BurgerStocksLabel = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        ButtonPanel.setBackground(new java.awt.Color(0, 102, 102));
        ButtonPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TwentyphpButton.setBackground(new java.awt.Color(0, 204, 204));
        TwentyphpButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TwentyphpButton.setForeground(new java.awt.Color(255, 255, 255));
        TwentyphpButton.setText("20 PHP");
        TwentyphpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TwentyphpButtonActionPerformed(evt);
            }
        });

        HundredphpButton.setBackground(new java.awt.Color(0, 204, 204));
        HundredphpButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        HundredphpButton.setForeground(new java.awt.Color(255, 255, 255));
        HundredphpButton.setText("100 PHP");
        HundredphpButton.setActionCommand("30 PHP");
        HundredphpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HundredphpButtonActionPerformed(evt);
            }
        });

        TenphpButton.setBackground(new java.awt.Color(0, 204, 204));
        TenphpButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TenphpButton.setForeground(new java.awt.Color(255, 255, 255));
        TenphpButton.setText("10 PHP");
        TenphpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TenphpButtonActionPerformed(evt);
            }
        });

        ThirtyphpButton.setBackground(new java.awt.Color(0, 204, 204));
        ThirtyphpButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ThirtyphpButton.setForeground(new java.awt.Color(255, 255, 255));
        ThirtyphpButton.setText("30 PHP");
        ThirtyphpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThirtyphpButtonActionPerformed(evt);
            }
        });

        FiftyphpButton.setBackground(new java.awt.Color(0, 204, 204));
        FiftyphpButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        FiftyphpButton.setForeground(new java.awt.Color(255, 255, 255));
        FiftyphpButton.setText("50 PHP");
        FiftyphpButton.setActionCommand("30 PHP");
        FiftyphpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiftyphpButtonActionPerformed(evt);
            }
        });

        LazatinMachineLabel.setBackground(new java.awt.Color(0, 204, 204));
        LazatinMachineLabel.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        LazatinMachineLabel.setForeground(new java.awt.Color(255, 255, 255));
        LazatinMachineLabel.setText("Lazatin Machine.co");
        LazatinMachineLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Webp.net-resizeimage.png"))); // NOI18N
        jLabel11.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.pink));

        TotalBalance.setBackground(new java.awt.Color(0, 204, 204));
        TotalBalance.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        TotalBalance.setForeground(new java.awt.Color(255, 255, 255));
        TotalBalance.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        CashOutButton.setBackground(new java.awt.Color(0, 153, 153));
        CashOutButton.setFont(new java.awt.Font("Unispace", 0, 24)); // NOI18N
        CashOutButton.setForeground(new java.awt.Color(255, 255, 255));
        CashOutButton.setText("CASH OUT");
        CashOutButton.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.cyan));
        CashOutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CashOutButton.setName("Cheetos"); // NOI18N
        CashOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CashOutButtonActionPerformed(evt);
            }
        });

        BalanceLabel.setFont(new java.awt.Font("Unispace", 1, 24)); // NOI18N
        BalanceLabel.setForeground(new java.awt.Color(255, 255, 255));
        BalanceLabel.setText("Balance:");

        javax.swing.GroupLayout ButtonPanelLayout = new javax.swing.GroupLayout(ButtonPanel);
        ButtonPanel.setLayout(ButtonPanelLayout);
        ButtonPanelLayout.setHorizontalGroup(
            ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonPanelLayout.createSequentialGroup()
                .addGroup(ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ButtonPanelLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(HundredphpButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TenphpButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TwentyphpButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ThirtyphpButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FiftyphpButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(ButtonPanelLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(CashOutButton))
                    .addGroup(ButtonPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(BalanceLabel)
                        .addGap(31, 31, 31)
                        .addComponent(TotalBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ButtonPanelLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LazatinMachineLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        ButtonPanelLayout.setVerticalGroup(
            ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ButtonPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(LazatinMachineLabel)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(40, 40, 40)
                .addComponent(TenphpButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TwentyphpButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ThirtyphpButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FiftyphpButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(HundredphpButton)
                .addGroup(ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ButtonPanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(TotalBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ButtonPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(BalanceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(CashOutButton)
                .addGap(22, 22, 22))
        );

        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                // Show a message dialog when the label is clicked
                JOptionPane.showMessageDialog(null, "Founders of Machine.Co");
            }
        });

        ProductPanel.setBackground(new java.awt.Color(0, 102, 102));
        ProductPanel.setBorder(new javax.swing.border.MatteBorder(null));

        BeveragesLabel.setBackground(new java.awt.Color(0, 204, 204));
        BeveragesLabel.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        BeveragesLabel.setForeground(new java.awt.Color(255, 255, 255));
        BeveragesLabel.setText("Beverages");
        BeveragesLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        SnacksMachineLabel.setBackground(new java.awt.Color(0, 204, 204));
        SnacksMachineLabel.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        SnacksMachineLabel.setForeground(new java.awt.Color(255, 255, 255));
        SnacksMachineLabel.setText("SNACKS");
        SnacksMachineLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        BuyCheetosButton.setBackground(new java.awt.Color(0, 153, 153));
        BuyCheetosButton.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        BuyCheetosButton.setForeground(new java.awt.Color(255, 255, 255));
        BuyCheetosButton.setText("Buy: 50Php");
        BuyCheetosButton.setName("Cheetos"); // NOI18N
        BuyCheetosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuyCheetosButtonActionPerformed(evt);
            }
        });

        BuyBurgerButton.setBackground(new java.awt.Color(0, 153, 153));
        BuyBurgerButton.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        BuyBurgerButton.setForeground(new java.awt.Color(255, 255, 255));
        BuyBurgerButton.setText("Buy: 100Php");
        BuyBurgerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuyBurgerButtonActionPerformed(evt);
            }
        });

        BuyDoritosButton.setBackground(new java.awt.Color(0, 153, 153));
        BuyDoritosButton.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        BuyDoritosButton.setForeground(new java.awt.Color(255, 255, 255));
        BuyDoritosButton.setText("Buy: 30Php");
        BuyDoritosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuyDoritosButtonActionPerformed(evt);
            }
        });

        CokeLabel.setFont(new java.awt.Font("SimSun", 0, 24)); // NOI18N
        CokeLabel.setForeground(new java.awt.Color(255, 255, 255));
        CokeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coke.png"))); // NOI18N
        CokeLabel.setText("Coke");
        CokeLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        WaterLabel.setFont(new java.awt.Font("SimSun", 0, 24)); // NOI18N
        WaterLabel.setForeground(new java.awt.Color(255, 255, 255));
        WaterLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/water.png"))); // NOI18N
        WaterLabel.setText("Water");
        WaterLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        CoffeeLabel.setFont(new java.awt.Font("SimSun", 0, 24)); // NOI18N
        CoffeeLabel.setForeground(new java.awt.Color(255, 255, 255));
        CoffeeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coffee-cup.png"))); // NOI18N
        CoffeeLabel.setText("Mango Dragonfruit");
        CoffeeLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        BurgerLabel.setFont(new java.awt.Font("SimSun", 0, 24)); // NOI18N
        BurgerLabel.setForeground(new java.awt.Color(255, 255, 255));
        BurgerLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/burger.png"))); // NOI18N
        BurgerLabel.setText("Burger");
        BurgerLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        DoritosLabel.setFont(new java.awt.Font("SimSun", 0, 24)); // NOI18N
        DoritosLabel.setForeground(new java.awt.Color(255, 255, 255));
        DoritosLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chips.png"))); // NOI18N
        DoritosLabel.setText("Doritos");
        DoritosLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        CheetosLabel.setFont(new java.awt.Font("SimSun", 0, 24)); // NOI18N
        CheetosLabel.setForeground(new java.awt.Color(255, 255, 255));
        CheetosLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chips.png"))); // NOI18N
        CheetosLabel.setText("Cheetos");
        CheetosLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        CheetosLabel.setName(""); // NOI18N

        BuyCoffeeButton.setBackground(new java.awt.Color(0, 153, 153));
        BuyCoffeeButton.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        BuyCoffeeButton.setForeground(new java.awt.Color(255, 255, 255));
        BuyCoffeeButton.setText("Buy: 120Php");
        BuyCoffeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuyCoffeeButtonActionPerformed(evt);
            }
        });

        BuyWaterButton.setBackground(new java.awt.Color(0, 153, 153));
        BuyWaterButton.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        BuyWaterButton.setForeground(new java.awt.Color(255, 255, 255));
        BuyWaterButton.setText("Buy: 10Php");
        BuyWaterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuyWaterButtonActionPerformed(evt);
            }
        });

        BuyCokeButton.setBackground(new java.awt.Color(0, 153, 153));
        BuyCokeButton.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        BuyCokeButton.setForeground(new java.awt.Color(255, 255, 255));
        BuyCokeButton.setText("Buy: 40Php");
        BuyCokeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuyCokeButtonActionPerformed(evt);
            }
        });

        DragonFruitStocksLabel.setForeground(new java.awt.Color(255, 255, 255));
        DragonFruitStocksLabel.setText("Available Stocks: 10");

        WaterStocksLabel.setForeground(new java.awt.Color(255, 255, 255));
        WaterStocksLabel.setText("Available Stocks: 10");

        CokeStocksLabel.setForeground(new java.awt.Color(255, 255, 255));
        CokeStocksLabel.setText("Available Stocks: 10");

        CheetosStocksLabel.setForeground(new java.awt.Color(255, 255, 255));
        CheetosStocksLabel.setText("Available Stocks: 10");

        DoritosStocksLabel.setForeground(new java.awt.Color(255, 255, 255));
        DoritosStocksLabel.setText("Available Stocks: 10");

        BurgerStocksLabel.setForeground(new java.awt.Color(255, 255, 255));
        BurgerStocksLabel.setText("Available Stocks: 10");

        javax.swing.GroupLayout ProductPanelLayout = new javax.swing.GroupLayout(ProductPanel);
        ProductPanel.setLayout(ProductPanelLayout);
        ProductPanelLayout.setHorizontalGroup(
            ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductPanelLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductPanelLayout.createSequentialGroup()
                        .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BuyCheetosButton)
                            .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(ProductPanelLayout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(BuyCokeButton))
                                .addGroup(ProductPanelLayout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(CokeLabel)))
                            .addComponent(CokeStocksLabel)
                            .addComponent(CheetosStocksLabel))
                        .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(ProductPanelLayout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(ProductPanelLayout.createSequentialGroup()
                                        .addComponent(WaterStocksLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(DragonFruitStocksLabel)
                                        .addGap(81, 81, 81))
                                    .addGroup(ProductPanelLayout.createSequentialGroup()
                                        .addComponent(BuyWaterButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BuyCoffeeButton)
                                        .addGap(78, 78, 78))
                                    .addGroup(ProductPanelLayout.createSequentialGroup()
                                        .addComponent(WaterLabel)
                                        .addGap(51, 51, 51)
                                        .addComponent(CoffeeLabel)
                                        .addGap(20, 20, 20))))
                            .addGroup(ProductPanelLayout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(DoritosStocksLabel)
                                    .addComponent(BuyDoritosButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BurgerStocksLabel)
                                .addGap(69, 69, 69))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductPanelLayout.createSequentialGroup()
                        .addComponent(CheetosLabel)
                        .addGap(114, 114, 114)
                        .addComponent(DoritosLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BurgerLabel)
                            .addComponent(BuyBurgerButton))
                        .addGap(67, 67, 67))))
            .addGroup(ProductPanelLayout.createSequentialGroup()
                .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductPanelLayout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(SnacksMachineLabel))
                    .addGroup(ProductPanelLayout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(BeveragesLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ProductPanelLayout.setVerticalGroup(
            ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(SnacksMachineLabel)
                .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductPanelLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BurgerLabel)
                            .addComponent(DoritosLabel)
                            .addComponent(CheetosLabel))
                        .addGap(65, 65, 65)
                        .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BuyDoritosButton)
                            .addComponent(BuyCheetosButton)
                            .addComponent(BuyBurgerButton))
                        .addGap(35, 35, 35)
                        .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CheetosStocksLabel)
                            .addComponent(DoritosStocksLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BurgerStocksLabel)
                        .addGap(60, 60, 60)))
                .addComponent(BeveragesLabel)
                .addGap(52, 52, 52)
                .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductPanelLayout.createSequentialGroup()
                        .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BuyCokeButton)
                            .addComponent(BuyWaterButton)
                            .addComponent(BuyCoffeeButton))
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductPanelLayout.createSequentialGroup()
                        .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CokeLabel)
                            .addComponent(WaterLabel)
                            .addComponent(CoffeeLabel))
                        .addGap(130, 130, 130)))
                .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DragonFruitStocksLabel)
                    .addComponent(WaterStocksLabel)
                    .addComponent(CokeStocksLabel))
                .addGap(94, 94, 94))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ProductPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ProductPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TwentyphpButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_TwentyphpButtonActionPerformed
        totalMoney += 20.0;
        // Update the display
        TotalBalance.setText("PHP " + totalMoney);
        TotalBalance.setVisible(true);
        JOptionPane.showMessageDialog(this, "Inserted: 20 Php");

    }// GEN-LAST:event_TwentyphpButtonActionPerformed

    private void HundredphpButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_HundredphpButtonActionPerformed
        totalMoney += 100.0;
        // Update the display
        TotalBalance.setText("PHP " + totalMoney);
        TotalBalance.setVisible(true);
        JOptionPane.showMessageDialog(this, "Inserted: 100 Php");

    }// GEN-LAST:event_HundredphpButtonActionPerformed

    private void TenphpButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_TenphpButtonActionPerformed
        totalMoney += 10.0;
        // Update the display
        TotalBalance.setText("PHP " + totalMoney);
        TotalBalance.setVisible(true);
        JOptionPane.showMessageDialog(this, "Inserted: 10 Php");
    }// GEN-LAST:event_TenphpButtonActionPerformed

    private void ThirtyphpButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ThirtyphpButtonActionPerformed
        totalMoney += 30.0;
        // Update the display
        TotalBalance.setText("PHP " + totalMoney);
        TotalBalance.setVisible(true);
        JOptionPane.showMessageDialog(this, "Inserted: 30 Php");

    }// GEN-LAST:event_ThirtyphpButtonActionPerformed

    private void FiftyphpButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_FiftyphpButtonActionPerformed
        totalMoney += 50.0;
        // Update the display
        TotalBalance.setText("PHP " + totalMoney);
        TotalBalance.setVisible(true);
        JOptionPane.showMessageDialog(this, "Inserted: 50 Php");
    }// GEN-LAST:event_FiftyphpButtonActionPerformed

    private void BuyCokeButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BuyCokeButtonActionPerformed
        if (cokeAvailability > 0) {
            if (totalMoney >= 40.0) {
                int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to buy Coke?", "Confirmation",
                        JOptionPane.YES_NO_OPTION);
                if (confirm == JOptionPane.YES_OPTION) {
                    buyProduct(new Coke(), 40.0, cokeAvailability);
                    cokeAvailability--;
                    CokeStocks(cokeAvailability);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Insufficient funds.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Coke is out of stock.");
        }
    }// GEN-LAST:event_BuyCokeButtonActionPerformed

    private void BuyCheetosButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BuyCheetosButtonActionPerformed
        if (cheetosAvailability > 0) {
            if (totalMoney >= 50.0) {
                int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to buy Cheetos?", "Confirmation",
                        JOptionPane.YES_NO_OPTION);
                if (confirm == JOptionPane.YES_OPTION) {
                    buyProduct(new Cheetos(), 50.0, cheetosAvailability);
                    cheetosAvailability--;
                    CheetosStocks(cheetosAvailability);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Insufficient funds.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Cheetos are out of stock.");
        }
    }// GEN-LAST:event_BuyCheetosButtonActionPerformed

    private void BuyDoritosButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BuyDoritosButtonActionPerformed
        if (doritosAvailability > 0) { // Check if Doritos are available
            if (totalMoney >= 30.0) {
                int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to buy Doritos?", "Confirmation",
                        JOptionPane.YES_NO_OPTION);
                if (confirm == JOptionPane.YES_OPTION) {
                    buyProduct(new Doritos(), 30.0, doritosAvailability);
                    doritosAvailability--;
                    DoritosStocks(doritosAvailability); // Update the display of available Doritos
                }
            } else {
                JOptionPane.showMessageDialog(this, "Insufficient funds.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Doritos are out of stock.");
        }
    }// GEN-LAST:event_BuyDoritosButtonActionPerformed

    private void BuyBurgerButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BuyBurgerButtonActionPerformed
        if (burgerAvailability > 0) {
            if (totalMoney >= 100.0) {
                int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to buy Burger?", "Confirmation",
                        JOptionPane.YES_NO_OPTION);
                if (confirm == JOptionPane.YES_OPTION) {
                    buyProduct(new Burger(), 100.0, burgerAvailability);
                    burgerAvailability--;
                    BurgerStocks(burgerAvailability);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Insufficient funds.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Burger is out of stock.");
        }
    }// GEN-LAST:event_BuyBurgerButtonActionPerformed

    private void BuyWaterButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BuyWaterButtonActionPerformed
        if (waterAvailability > 0) {
            if (totalMoney >= 10.0) {
                int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to buy Water?", "Confirmation",
                        JOptionPane.YES_NO_OPTION);
                if (confirm == JOptionPane.YES_OPTION) {
                    buyProduct(new Water(), 10.0, waterAvailability);
                    waterAvailability--;
                    WaterStocks(waterAvailability);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Insufficient funds.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Water is out of stock.");
        }
    }// GEN-LAST:event_BuyWaterButtonActionPerformed

    private void BuyCoffeeButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BuyCoffeeButtonActionPerformed
        if (coffeeAvailability > 0) { // Check if Coffee is available
            if (totalMoney >= 120.0) {
                int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to buy Coffee?", "Confirmation",
                        JOptionPane.YES_NO_OPTION);
                if (confirm == JOptionPane.YES_OPTION) {
                    buyProduct(new Coffee(), 120.0, coffeeAvailability);
                    coffeeAvailability--;
                    DragonFruitStocks(coffeeAvailability); // Update the display of available Coffee
                }
            } else {
                JOptionPane.showMessageDialog(this, "Insufficient funds.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Coffee is out of stock.");
        }
    }// GEN-LAST:event_BuyCoffeeButtonActionPerformed

    private void CashOutButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_CashOutButtonActionPerformed
        int option = JOptionPane.showConfirmDialog(this, "Do you want to cash out the remaining balance?", "Cash Out",
                JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, "Remaining Funds: PHP " + totalMoney);
            if (totalMoney == 0) {
                JOptionPane.showMessageDialog(this, "You have no balance");
            } else {
                JOptionPane.showMessageDialog(this, "Cashing Out: PHP " + totalMoney);
                totalMoney = 0.0;
                TotalBalance.setText("PHP " + totalMoney);
            }
        }
    }// GEN-LAST:event_CashOutButtonActionPerformed

    private void buyProduct(Product product, double price, int availability) {
        if (availability > 0) {
            if (totalMoney >= price) {
                totalMoney -= price;
                TotalBalance.setText("PHP " + totalMoney);
                TotalBalance.setVisible(true);
                TotalBalance.repaint();
                JOptionPane.showMessageDialog(this,
                        "Thank you for purchasing " + product.getName() + ". Your Balance: PHP " + totalMoney);
            } else {
                JOptionPane.showMessageDialog(this, "Insufficient funds.");
            }
        } else {
            JOptionPane.showMessageDialog(this, product.getName() + " is out of stock.");
        }
    }

    private void WaterStocks(int availability) {
        WaterStocksLabel.setText("Available Stocks: " + availability); // Display the number of available stocks
    }

    private void CokeStocks(int availability) {
        CokeStocksLabel.setText("Available Stocks: " + availability); // Display the number of available stocks
    }

    private void DragonFruitStocks(int availability) {
        DragonFruitStocksLabel.setText("Available Stocks: " + availability); // Display the number of available stocks
    }

    private void CheetosStocks(int availability) {
        CheetosStocksLabel.setText("Available Stocks: " + availability); // Display the number of available stocks
    }

    private void DoritosStocks(int availability) {
        DoritosStocksLabel.setText("Available Stocks: " + availability); // Display the number of available stocks
    }

    private void BurgerStocks(int availability) {
        BurgerStocksLabel.setText("Available Stocks: " + availability); // Display the number of available stocks
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BalanceLabel;
    private javax.swing.JLabel BeveragesLabel;
    private javax.swing.JLabel BurgerLabel;
    private javax.swing.JLabel BurgerStocksLabel;
    private javax.swing.JPanel ButtonPanel;
    private javax.swing.JButton BuyBurgerButton;
    private javax.swing.JButton BuyCheetosButton;
    private javax.swing.JButton BuyCoffeeButton;
    private javax.swing.JButton BuyCokeButton;
    private javax.swing.JButton BuyDoritosButton;
    private javax.swing.JButton BuyWaterButton;
    private javax.swing.JButton CashOutButton;
    private javax.swing.JLabel CheetosLabel;
    private javax.swing.JLabel CheetosStocksLabel;
    private javax.swing.JLabel CoffeeLabel;
    private javax.swing.JLabel CokeLabel;
    private javax.swing.JLabel CokeStocksLabel;
    private javax.swing.JLabel DoritosLabel;
    private javax.swing.JLabel DoritosStocksLabel;
    private javax.swing.JLabel DragonFruitStocksLabel;
    private javax.swing.JButton FiftyphpButton;
    private javax.swing.JButton HundredphpButton;
    private javax.swing.JLabel LazatinMachineLabel;
    private javax.swing.JPanel ProductPanel;
    private javax.swing.JLabel SnacksMachineLabel;
    private javax.swing.JButton TenphpButton;
    private javax.swing.JButton ThirtyphpButton;
    private javax.swing.JLabel TotalBalance;
    private javax.swing.JButton TwentyphpButton;
    private javax.swing.JLabel WaterLabel;
    private javax.swing.JLabel WaterStocksLabel;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
